all: Student Hello String iq1_1

iq1_1:
	javac iq1_1.java
	java iq1_1

Student:
	javac Student.java
String:
	javac StringBufferTest.java
Hello:
	javac HelloWorld.java

test:
	java Student

clean:
	rm *.class *~